### ISSUE TITLE
Got num_samples=0 error when trying to train the model

### ISSUE THREAD

**Issue by MaxtuneLee** [kylevedder/zeroflow#3]
Thank you for your work.

Following the README and GETTING_STARTED document, I created the train and val supervision labels, and my dataset folder structure follows this: 
```
|-argoverse2
    |-train
    |-train_sceneflow
    |-test
    |-val
    |-val_sceneflow
```
I mounted the folder to the container correctly as shown below:
```
root@Max-laptop-debian:/efs# ls
argoverse2
root@Max-laptop-debian:/efs# cd argoverse2/
root@Max-laptop-debian:/efs/argoverse2# ls
test  train  train_sceneflow  val  val_sceneflow
```
However, when I try to train the model using 
```
python train_pl.py ./configs/fastflow3d/argo/nsfp_distilatation_speed_scaled_updated.py
```
I always got the num_samples=0 error below
```
Traceback (most recent call last):
  File "/project/train_pl.py", line 189, in <module>
    main()
  File "/project/train_pl.py", line 146, in main
    train_dataloader = make_train_dataloader(cfg)
  File "/project/train_pl.py", line 68, in make_train_dataloader
    return torch.utils.data.DataLoader(train_dataset,
  File "/miniconda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 353, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/miniconda/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```
The paths inside `nsfp_distilatation_speed_scaled_updated.py` are:
```
train_sequence_dir = "/efs/argoverse2/train/"
train_flow_dir = "/efs/argoverse2/train_sceneflow/"

test_sequence_dir = "/efs/argoverse2/val/"
test_flow_dir = "/efs/argoverse2/val_sceneflow/"
```
I believe the problem is that the train path in the config file is incorrect. However, I am unable to find additional information in the document to solve my question. Would you mind pointing out what's wrong with it?

**Comment by kylevedder** [comment]
Hello, your issue is that you are trying to train ZeroFlow, which uses NSFP pseudolabels, but you do not have the NSFP pseudolabels to train your distillation student upon (we haven't released them yet, they are big enough that it's a pain to find hosting).

This is why the base distillation config has 

```
train_sequence_dir = "/efs/argoverse2/train/"
train_flow_dir = "/efs/argoverse2/train_nsfp_flow/"
```

listed -- it is training on the `train_nsfp_flow/` labels.

If you want to get started reproducing our ZeroFlow results, you can run NSFP yourself (NB: this will take awhile unless you have a bunch of idle GPUs lying around) or you can try to train the FastFlow3D baseline model with

```
python train_pl.py configs/fastflow3d/argo/supervised.py
```

Note that we used 4 A6000 GPUs to train this, so you may have to fiddle with the batch size and turn on gradient accumulation ([this is supported by the config](https://github.com/kylevedder/zeroflow/blob/master/train_pl.py#L196-L197)) to get to the batch size of 64 we used to train the model. Alternatively, if you want to play with the trained models you can download the weights from our [weight repo](https://github.com/kylevedder/zeroflow_weights).
